#### Automl

In [24]:
from flaml import AutoML
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

# 1. Load data
X, y = fetch_california_housing(return_X_y=True)

# 2. Split into train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, shuffle=True
)

# 3. Initialize and fit AutoML
automl = AutoML()
automl_settings = {
    "time_budget": 60,
    "metric": "r2",
    "task": "regression",
    "log_file_name": "flaml.log",
    "n_splits": 5,  # Use 5-fold cross-validation
}
automl.fit(X_train=X_train, y_train=y_train, **automl_settings)

# 4. Predict on test set
y_pred = automl.predict(X_test)

# 5. Compute and print metrics
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)  # Compute MSE
rmse = mse ** 0.5  # Compute RMSE manually
mae = mean_absolute_error(y_test, y_pred)

print(f"Test R²: {r2:.4f}")
print(f"Test RMSE: {rmse:.4f}")
print(f"Test MAE: {mae:.4f}")

[flaml.automl.logger: 05-01 21:18:26] {1728} INFO - task = regression
[flaml.automl.logger: 05-01 21:18:26] {1739} INFO - Evaluation method: cv
[flaml.automl.logger: 05-01 21:18:26] {1838} INFO - Minimizing error metric: 1-r2
[flaml.automl.logger: 05-01 21:18:26] {1955} INFO - List of ML learners in AutoML Run: ['lgbm', 'rf', 'xgboost', 'extra_tree', 'xgb_limitdepth', 'sgd']
[flaml.automl.logger: 05-01 21:18:26] {2258} INFO - iteration 0, current learner lgbm
[flaml.automl.logger: 05-01 21:18:26] {2393} INFO - Estimated sufficient time budget=2730s. Estimated necessary time budget=20s.
[flaml.automl.logger: 05-01 21:18:26] {2442} INFO -  at 0.3s,	estimator lgbm's best error=0.7333,	best estimator lgbm's best error=0.7333
[flaml.automl.logger: 05-01 21:18:26] {2258} INFO - iteration 1, current learner lgbm

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:26] {2442} INFO -  at 0.5s,	estimator lgbm's best error=0.7333,	best estimator lgbm's best error=0.7333
[flaml.automl.logger: 05-01 21:18:26] {2258} INFO - iteration 2, current learner lgbm

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:26] {2442} INFO -  at 0.7s,	estimator lgbm's best error=0.5278,	best estimator lgbm's best error=0.5278
[flaml.automl.logger: 05-01 21:18:26] {2258} INFO - iteration 3, current learner sgd
[flaml.automl.logger: 05-01 21:18:26] {2442} INFO -  at 0.8s,	estimator sgd's best error=1.0592,	best estimator lgbm's best error=0.5278
[flaml.automl.logger: 05-01 21:18:26] {2258} INFO - iteration 4, current learner lgbm

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:27] {2442} INFO -  at 1.1s,	estimator lgbm's best error=0.2823,	best estimator lgbm's best error=0.2823
[flaml.automl.logger: 05-01 21:18:27] {2258} INFO - iteration 5, current learner sgd
[flaml.automl.logger: 05-01 21:18:27] {2442} INFO -  at 1.2s,	estimator sgd's best error=1.0592,	best estimator lgbm's best error=0.2823
[flaml.automl.logger: 05-01 21:18:27] {2258} INFO - iteration 6, current learner lgbm

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:27] {2442} INFO -  at 1.4s,	estimator lgbm's best error=0.2823,	best estimator lgbm's best error=0.2823
[flaml.automl.logger: 05-01 21:18:27] {2258} INFO - iteration 7, current learner lgbm

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:28] {2442} INFO -  at 1.9s,	estimator lgbm's best error=0.2612,	best estimator lgbm's best error=0.2612
[flaml.automl.logger: 05-01 21:18:28] {2258} INFO - iteration 8, current learner lgbm

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:28] {2442} INFO -  at 2.3s,	estimator lgbm's best error=0.2612,	best estimator lgbm's best error=0.2612
[flaml.automl.logger: 05-01 21:18:28] {2258} INFO - iteration 9, current learner sgd

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:28] {2442} INFO -  at 2.7s,	estimator sgd's best error=0.9874,	best estimator lgbm's best error=0.2612
[flaml.automl.logger: 05-01 21:18:28] {2258} INFO - iteration 10, current learner xgboost
[flaml.automl.logger: 05-01 21:18:29] {2442} INFO -  at 2.9s,	estimator xgboost's best error=0.7324,	best estimator lgbm's best error=0.2612
[flaml.automl.logger: 05-01 21:18:29] {2258} INFO - iteration 11, current learner xgboost
[flaml.automl.logger: 05-01 21:18:29] {2442} INFO -  at 3.1s,	estimator xgboost's best error=0.7324,	best estimator lgbm's best error=0.2612
[flaml.automl.logger: 05-01 21:18:29] {2258} INFO - iteration 12, current learner xgboost
[flaml.automl.logger: 05-01 21:18:29] {2442} INFO -  at 3.3s,	estimator xgboost's best error=0.5362,	best estimator lgbm's best error=0.2612
[flaml.automl.logger: 05-01 21:18:29] {2258} INFO - iteration 13, current learner extra_tree
[flaml.automl.logger: 05-01 21:18:29] {2442} INFO -  at 3.6s,	estimator extra_tree's best error=0.5949,	best estimator lgbm's best error=0.2612
[flaml.automl.logger: 05-01 21:18:29] {2258} INFO - iteration 14, current learner xgboost
[flaml.automl.logger: 05-01 21:18:30] {2442} INFO -  at 3.9s,	estimator xgboost's best error=0.3589,	best estimator lgbm's best error=0.2612
[flaml.automl.logger: 05-01 21:18:30] {2258} INFO - iteration 15, current learner extra_tree
[flaml.automl.logger: 05-01 21:18:30] {2442} INFO -  at 4.4s,	estimator extra_tree's best error=0.4304,	best estimator lgbm's best error=0.2612
[flaml.automl.logger: 05-01 21:18:30] {2258} INFO - iteration 16, current learner lgbm
[flaml.automl.logger: 05-01 21:18:30] {2442} INFO -  at 4.6s,	estimator lgbm's best error=0.2612,	best estimator lgbm's best error=0.2612
[flaml.automl.logger: 05-01 21:18:30] {2258} INFO - iteration 17, current learner extra_tree

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:31] {2442} INFO -  at 5.1s,	estimator extra_tree's best error=0.4304,	best estimator lgbm's best error=0.2612
[flaml.automl.logger: 05-01 21:18:31] {2258} INFO - iteration 18, current learner lgbm

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:32] {2442} INFO -  at 6.8s,	estimator lgbm's best error=0.2227,	best estimator lgbm's best error=0.2227
[flaml.automl.logger: 05-01 21:18:32] {2258} INFO - iteration 19, current learner xgboost

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:33] {2442} INFO -  at 7.0s,	estimator xgboost's best error=0.3589,	best estimator lgbm's best error=0.2227
[flaml.automl.logger: 05-01 21:18:33] {2258} INFO - iteration 20, current learner rf
[flaml.automl.logger: 05-01 21:18:33] {2442} INFO -  at 7.6s,	estimator rf's best error=0.5235,	best estimator lgbm's best error=0.2227
[flaml.automl.logger: 05-01 21:18:33] {2258} INFO - iteration 21, current learner rf
[flaml.automl.logger: 05-01 21:18:34] {2442} INFO -  at 8.1s,	estimator rf's best error=0.3725,	best estimator lgbm's best error=0.2227
[flaml.automl.logger: 05-01 21:18:34] {2258} INFO - iteration 22, current learner xgboost
[flaml.automl.logger: 05-01 21:18:34] {2442} INFO -  at 8.4s,	estimator xgboost's best error=0.3589,	best estimator lgbm's best error=0.2227
[flaml.automl.logger: 05-01 21:18:34] {2258} INFO - iteration 23, current learner lgbm

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:35] {2442} INFO -  at 8.9s,	estimator lgbm's best error=0.2227,	best estimator lgbm's best error=0.2227
[flaml.automl.logger: 05-01 21:18:35] {2258} INFO - iteration 24, current learner rf

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:35] {2442} INFO -  at 9.6s,	estimator rf's best error=0.3725,	best estimator lgbm's best error=0.2227
[flaml.automl.logger: 05-01 21:18:35] {2258} INFO - iteration 25, current learner extra_tree
[flaml.automl.logger: 05-01 21:18:36] {2442} INFO -  at 10.0s,	estimator extra_tree's best error=0.3736,	best estimator lgbm's best error=0.2227
[flaml.automl.logger: 05-01 21:18:36] {2258} INFO - iteration 26, current learner sgd
[flaml.automl.logger: 05-01 21:18:39] {2442} INFO -  at 13.7s,	estimator sgd's best error=0.9874,	best estimator lgbm's best error=0.2227
[flaml.automl.logger: 05-01 21:18:39] {2258} INFO - iteration 27, current learner rf
[flaml.automl.logger: 05-01 21:18:40] {2442} INFO -  at 14.7s,	estimator rf's best error=0.2996,	best estimator lgbm's best error=0.2227
[flaml.automl.logger: 05-01 21:18:40] {2258} INFO - iteration 28, current learner xgboost
[flaml.automl.logger: 05-01 21:18:41] {2442} INFO -  at 15.1s,	estimator xgboost's best error=0.2770,	best estimator lgbm's best error=0.2227
[flaml.automl.logger: 05-01 21:18:41] {2258} INFO - iteration 29, current learner xgboost
[flaml.automl.logger: 05-01 21:18:42] {2442} INFO -  at 15.8s,	estimator xgboost's best error=0.2650,	best estimator lgbm's best error=0.2227
[flaml.automl.logger: 05-01 21:18:42] {2258} INFO - iteration 30, current learner extra_tree
[flaml.automl.logger: 05-01 21:18:42] {2442} INFO -  at 16.3s,	estimator extra_tree's best error=0.2973,	best estimator lgbm's best error=0.2227
[flaml.automl.logger: 05-01 21:18:42] {2258} INFO - iteration 31, current learner lgbm

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:47] {2442} INFO -  at 20.8s,	estimator lgbm's best error=0.1656,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:18:47] {2258} INFO - iteration 32, current learner lgbm

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:53] {2442} INFO -  at 27.0s,	estimator lgbm's best error=0.1656,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:18:53] {2258} INFO - iteration 33, current learner rf

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:53] {2442} INFO -  at 27.6s,	estimator rf's best error=0.2538,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:18:53] {2258} INFO - iteration 34, current learner extra_tree
[flaml.automl.logger: 05-01 21:18:54] {2442} INFO -  at 28.1s,	estimator extra_tree's best error=0.2973,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:18:54] {2258} INFO - iteration 35, current learner lgbm

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:57] {2442} INFO -  at 31.5s,	estimator lgbm's best error=0.1656,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:18:57] {2258} INFO - iteration 36, current learner rf

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:18:58] {2442} INFO -  at 32.1s,	estimator rf's best error=0.2538,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:18:58] {2258} INFO - iteration 37, current learner extra_tree
[flaml.automl.logger: 05-01 21:18:58] {2442} INFO -  at 32.7s,	estimator extra_tree's best error=0.2490,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:18:58] {2258} INFO - iteration 38, current learner xgboost
[flaml.automl.logger: 05-01 21:18:59] {2442} INFO -  at 33.2s,	estimator xgboost's best error=0.2534,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:18:59] {2258} INFO - iteration 39, current learner extra_tree
[flaml.automl.logger: 05-01 21:18:59] {2442} INFO -  at 33.7s,	estimator extra_tree's best error=0.2490,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:18:59] {2258} INFO - iteration 40, current learner rf
[flaml.automl.logger: 05-01 21:19:00] {2442} INFO -  at 34.4s,	estimator rf's best error=0.2353,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:19:00] {2258} INFO - iteration 41, current learner extra_tree
[flaml.automl.logger: 05-01 21:19:01] {2442} INFO -  at 35.1s,	estimator extra_tree's best error=0.2348,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:19:01] {2258} INFO - iteration 42, current learner extra_tree
[flaml.automl.logger: 05-01 21:19:01] {2442} INFO -  at 35.6s,	estimator extra_tree's best error=0.2348,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:19:01] {2258} INFO - iteration 43, current learner lgbm

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:19:09] {2442} INFO -  at 43.1s,	estimator lgbm's best error=0.1656,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:19:09] {2258} INFO - iteration 44, current learner xgboost

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:19:09] {2442} INFO -  at 43.6s,	estimator xgboost's best error=0.2180,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:19:09] {2258} INFO - iteration 45, current learner extra_tree
[flaml.automl.logger: 05-01 21:19:10] {2442} INFO -  at 44.1s,	estimator extra_tree's best error=0.2268,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:19:10] {2258} INFO - iteration 46, current learner xgboost
[flaml.automl.logger: 05-01 21:19:10] {2442} INFO -  at 44.5s,	estimator xgboost's best error=0.2180,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:19:10] {2258} INFO - iteration 47, current learner xgboost
[flaml.automl.logger: 05-01 21:19:11] {2442} INFO -  at 44.9s,	estimator xgboost's best error=0.2180,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:19:11] {2258} INFO - iteration 48, current learner xgboost
[flaml.automl.logger: 05-01 21:19:11] {2442} INFO -  at 45.7s,	estimator xgboost's best error=0.1911,	best estimator lgbm's best error=0.1656
[flaml.automl.logger: 05-01 21:19:11] {2258} INFO - iteration 49, current learner lgbm

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:19:15] {2442} INFO -  at 49.1s,	estimator lgbm's best error=0.1609,	best estimator lgbm's best error=0.1609
[flaml.automl.logger: 05-01 21:19:15] {2258} INFO - iteration 50, current learner xgboost

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:19:15] {2442} INFO -  at 49.6s,	estimator xgboost's best error=0.1911,	best estimator lgbm's best error=0.1609
[flaml.automl.logger: 05-01 21:19:15] {2258} INFO - iteration 51, current learner extra_tree
[flaml.automl.logger: 05-01 21:19:16] {2442} INFO -  at 50.0s,	estimator extra_tree's best error=0.2268,	best estimator lgbm's best error=0.1609
[flaml.automl.logger: 05-01 21:19:16] {2258} INFO - iteration 52, current learner rf
[flaml.automl.logger: 05-01 21:19:17] {2442} INFO -  at 51.1s,	estimator rf's best error=0.2353,	best estimator lgbm's best error=0.1609
[flaml.automl.logger: 05-01 21:19:17] {2258} INFO - iteration 53, current learner xgboost
[flaml.automl.logger: 05-01 21:19:19] {2442} INFO -  at 53.2s,	estimator xgboost's best error=0.1911,	best estimator lgbm's best error=0.1609
[flaml.automl.logger: 05-01 21:19:19] {2258} INFO - iteration 54, current learner lgbm

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:19:23] {2442} INFO -  at 57.6s,	estimator lgbm's best error=0.1609,	best estimator lgbm's best error=0.1609
[flaml.automl.logger: 05-01 21:19:23] {2258} INFO - iteration 55, current learner rf

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[flaml.automl.logger: 05-01 21:19:24] {2442} INFO -  at 58.2s,	estimator rf's best error=0.2135,	best estimator lgbm's best error=0.1609
[flaml.automl.logger: 05-01 21:19:24] {2258} INFO - iteration 56, current learner xgboost
[flaml.automl.logger: 05-01 21:19:24] {2442} INFO -  at 58.7s,	estimator xgboost's best error=0.1911,	best estimator lgbm's best error=0.1609
[flaml.automl.logger: 05-01 21:19:24] {2258} INFO - iteration 57, current learner rf
[flaml.automl.logger: 05-01 21:19:25] {2442} INFO -  at 59.3s,	estimator rf's best error=0.2135,	best estimator lgbm's best error=0.1609
[flaml.automl.logger: 05-01 21:19:25] {2258} INFO - iteration 58, current learner rf
[flaml.automl.logger: 05-01 21:19:26] {2442} INFO -  at 60.1s,	estimator rf's best error=0.2135,	best estimator lgbm's best error=0.1609
[flaml.automl.logger: 05-01 21:19:27] {2685} INFO - retrain lgbm for 0.7s
[flaml.automl.logger: 05-01 21:19:27] {2688} INFO - retrained model: LGBMRegressor(colsample_bytree=np.float64(0.5967846088487322),
              learning_rate=np.float64(0.09348689572544734), max_bin=127,
              min_child_samples=4, n_estimators=90, n_jobs=-1, num_leaves=75,
              reg_alpha=np.float64(0.006958608037974516),
              reg_lambda=np.float64(0.001895876878997586), verbose=-1)
[flaml.automl.logger: 05-01 21:19:27] {1985} INFO - fit succeeded
[flaml.automl.logger: 05-01 21:19:27] {1986} INFO - Time taken to find the best model: 49.08169770240784
Test R²: 0.8399
Test RMSE: 0.4581
Test MAE: 0.3034

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [6]:
# Print the best model used by FLAML
print(f"Best model: {automl.best_estimator}")

Best model: lgbm

In [25]:
import pandas as pd
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

# Extract information about all models tried
leaderboard_data = []
for estimator, config in automl.best_config_per_estimator.items():
    
    # Get predictions for the test set
    y_pred = automl.predict(X_test)
    
    # Compute metrics
    r2 = r2_score(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = mse ** 0.5
    mae = mean_absolute_error(y_test, y_pred)
    
    # Add to leaderboard data
    leaderboard_data.append({
        "Estimator": estimator,
        "R²": r2,
        "RMSE": rmse,
        "MAE": mae,
        "Best Config": config
    })

# Create a DataFrame for the leaderboard
leaderboard_df = pd.DataFrame(leaderboard_data)

# Sort by R² (higher is better for R²)
leaderboard_df = leaderboard_df.sort_values(by="R²", ascending=False)

# Display the leaderboard
print("FLAML Leaderboard:")
leaderboard_df

FLAML Leaderboard:

c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\nicoz\Desktop\nico\optimization\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

,Estimator,R²,RMSE,MAE,Best Config
0,lgbm,0.839887,0.458055,0.303441,"{'n_estimators': 90, 'num_leaves': 75, 'min_ch..."
1,rf,0.839887,0.458055,0.303441,"{'n_estimators': 5, 'max_features': 0.56961843..."
2,xgboost,0.839887,0.458055,0.303441,"{'n_estimators': 20, 'max_leaves': 22, 'min_ch..."
3,extra_tree,0.839887,0.458055,0.303441,"{'n_estimators': 6, 'max_features': 0.64195068..."
4,xgb_limitdepth,0.839887,0.458055,0.303441,None
5,sgd,0.839887,0.458055,0.303441,"{'penalty': 'l2', 'alpha': 2.0738278600666822e..."

#### Autogluon

In [28]:
from autogluon.tabular import TabularPredictor
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import pandas as pd

# 1. Load data
X, y = fetch_california_housing(return_X_y=True)
data = pd.DataFrame(X, columns=["Feature_" + str(i) for i in range(X.shape[1])])
data["Target"] = y

# 2. Split into train/test
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42, shuffle=True)

# 3. Initialize AutoGluon TabularPredictor with K-fold cross-validation
predictor = TabularPredictor(
    label="Target", 
    eval_metric="r2"  # Optimize for R²
).fit(
    train_data=train_data,
    time_limit=60,  # Time budget in seconds
    presets="best_quality",  # Use best quality settings (includes hyperparameter optimization)
    num_bag_folds=5  # Enable 5-fold cross-validation
)

# 4. Evaluate on the test set
y_test = test_data["Target"]
y_pred = predictor.predict(test_data)

# Compute metrics
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
mae = mean_absolute_error(y_test, y_pred)

print(f"Test R²: {r2:.4f}")
print(f"Test RMSE: {rmse:.4f}")
print(f"Test MAE: {mae:.4f}")

# 5. Generate leaderboard for the test set
leaderboard = predictor.leaderboard(test_data, extra_metrics=["r2", "rmse", "mae"])
print(leaderboard)

No path specified. Models will be saved in: "AutogluonModels\ag-20250501_133957"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.2
Python Version:     3.12.0
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26100
CPU Count:          8
Memory Avail:       3.59 GB / 15.70 GB (22.9%)
Disk Space Avail:   282.62 GB / 456.03 GB (62.0%)
===================================================
Presets specified: ['best_quality']
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=5, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 15s of the 60s of remaining time (25%).
		Context path: "c:\Users\nicoz\Desktop\nico\optimization\AutogluonModels\ag-20250501_133957\ds_sub_fit\sub_fit_ho"
Leaderboard on holdout data (DyStack):
                   model  score_holdout  score_val eval_metric  pred_time_test  pred_time_val   fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0      LightGBMXT_BAG_L1       0.828847   0.832279          r2        1.378255       2.928490  22.370902                 1.378255                2.928490          22.370902            1       True          3
1    WeightedEnsemble_L2       0.828847   0.832279          r2        1.394765       2.929490  22.427423                 0.016510                0.001001           0.056521            2       True          4
2    WeightedEnsemble_L3       0.828847   0.832279          r2        1.395255       2.929488  22.439902                 0.017000                0.000999           0.069000            3       True          5
3  KNeighborsDist_BAG_L1       0.176499   0.159679          r2        0.064515       0.040691   0.021998                 0.064515                0.040691           0.021998            1       True          2
4  KNeighborsUnif_BAG_L1       0.161896   0.135437          r2        0.083517       0.039579   0.024063                 0.083517                0.039579           0.024063            1       True          1
	1	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: False)
	44s	 = DyStack   runtime |	16s	 = Remaining runtime
Starting main fit with num_stack_levels=1.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=1)`
Beginning AutoGluon training ... Time limit = 16s
AutoGluon will save models to "c:\Users\nicoz\Desktop\nico\optimization\AutogluonModels\ag-20250501_133957"
Train Data Rows:    16512
Train Data Columns: 8
Label Column:       Target
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    2472.29 MB
	Train Data (Original)  Memory Usage: 1.01 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 8 | ['Feature_0', 'Feature_1', 'Feature_2', 'Feature_3', 'Feature_4', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 8 | ['Feature_0', 'Feature_1', 'Feature_2', 'Feature_3', 'Feature_4', ...]
	0.1s = Fit runtime
	8 features in original data used to generate 8 features in processed data.
	Train Data (Processed) Memory Usage: 1.01 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.11s ...
AutoGluon will gauge predictive performance using evaluation metric: 'r2'
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (112 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 108 L1 models, fit_strategy="sequential" ...
Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 10.72s of the 16.06s of remaining time.
	0.1576	 = Validation score   (r2)
	0.05s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 7.53s of the 12.88s of remaining time.
	0.1803	 = Validation score   (r2)
	0.04s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 7.39s of the 12.73s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.33%)
	0.8314	 = Validation score   (r2)
	20.15s	 = Training   runtime
	2.47s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 16.08s of the -14.84s of remaining time.
	Ensemble Weights: {'LightGBMXT_BAG_L1': 1.0}
	0.8314	 = Validation score   (r2)
	0.07s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting 106 L2 models, fit_strategy="sequential" ...
Fitting model: WeightedEnsemble_L3 ... Training model for up to 16.08s of the -15.11s of remaining time.
	Ensemble Weights: {'LightGBMXT_BAG_L1': 1.0}
	0.8314	 = Validation score   (r2)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 31.4s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 1338.9 rows/s (3303 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\nicoz\Desktop\nico\optimization\AutogluonModels\ag-20250501_133957")

Test R²: 0.8317
Test RMSE: 0.4696
Test MAE: 0.3115
                   model  score_test        r2  root_mean_squared_error  \
0      LightGBMXT_BAG_L1    0.831724  0.831724                -0.469586
1    WeightedEnsemble_L2    0.831724  0.831724                -0.469586
2    WeightedEnsemble_L3    0.831724  0.831724                -0.469586
3  KNeighborsDist_BAG_L1    0.171780  0.171780                -1.041781
4  KNeighborsUnif_BAG_L1    0.146310  0.146310                -1.057678

   mean_absolute_error  score_val eval_metric  pred_time_test  pred_time_val  \
0            -0.311539   0.831417          r2        0.822655       2.466738
1            -0.311539   0.831417          r2        0.824655       2.467740
2            -0.311539   0.831417          r2        0.844655       2.468730
3            -0.798966   0.180302          r2        0.104549       0.050545
4            -0.812798   0.157604          r2        0.109083       0.054058

    fit_time  pred_time_test_marginal  pred_time_val_marginal  \
0  20.151575                 0.822655                2.466738
1  20.218097                 0.002000                0.001002
2  20.213090                 0.022000                0.001992
3   0.037002                 0.104549                0.050545
4   0.045443                 0.109083                0.054058

   fit_time_marginal  stack_level  can_infer  fit_order
0          20.151575            1       True          3
1           0.066522            2       True          4
2           0.061516            3       True          5
3           0.037002            1       True          2
4           0.045443            1       True          1

In [29]:
leaderboard

,model,score_test,r2,root_mean_squared_error,mean_absolute_error,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,LightGBMXT_BAG_L1,0.831724,0.831724,-0.469586,-0.311539,0.831417,r2,0.822655,2.466738,20.151575,0.822655,2.466738,20.151575,1,True,3
1,WeightedEnsemble_L2,0.831724,0.831724,-0.469586,-0.311539,0.831417,r2,0.824655,2.467740,20.218097,0.002000,0.001002,0.066522,2,True,4
2,WeightedEnsemble_L3,0.831724,0.831724,-0.469586,-0.311539,0.831417,r2,0.844655,2.468730,20.213090,0.022000,0.001992,0.061516,3,True,5
3,KNeighborsDist_BAG_L1,0.171780,0.171780,-1.041781,-0.798966,0.180302,r2,0.104549,0.050545,0.037002,0.104549,0.050545,0.037002,1,True,2
4,KNeighborsUnif_BAG_L1,0.146310,0.146310,-1.057678,-0.812798,0.157604,r2,0.109083,0.054058,0.045443,0.109083,0.054058,0.045443,1,True,1